title: François Gervais
logo: /assets/img/logo.png
description: A firmware developer who likes making things.
show_downloads: false
github:
  is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
