title: François Gervais
logo: /assets/img/logo.png
description:
  I'm an embedded firmware developer with interest in communication
  protocols, computer security, machine learning and basic hardware development.
show_downloads: false
github:
  is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
